# Configuration for Repo Lockdown - https://github.com/dessant/repo-lockdown

# Close issues and pull requests
close: true

# Lock issues and pull requests
lock: true

# Optionally, specify configuration settings just for `issues` or `pulls`
issues:
  comment: |
    Thank you for your interest in the libvirt project.

    Since this repository is a read-only mirror of the project's master repostory hosted on GitLab, issues opened here are not processed.

    We kindly request that new issues are reported to

      https://gitlab.com/libvirt/libvirt/-/issues/new

    Thank you for your time and understanding.

pulls:
  comment: |
    Thank you for your interest in the libvirt project.

    Since this repository is a read-only mirror of the project's master repostory hosted on GitLab, merge requests opened here are not processed.

    We kindly request that contributors fork the project at

      https://gitlab.com/libvirt/libvirt/

    push changes to the fork, and then open a new merge request at

      https://gitlab.com/libvirt/libvirt/-/merge_requests/new

    Thank you for your time and understanding.
