#!/bin/sh
# ensure that defining with an invalid vCPU cpuset elicits a diagnostic

# Copyright (C) 2008-2009 Red Hat, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

test -z "$srcdir" && srcdir=$(pwd)
test -z "$abs_top_srcdir" && abs_top_srcdir=$(pwd)/..
test -z "$abs_top_builddir" && abs_top_builddir=$(pwd)/..

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/tools/virsh --version
fi

. "$srcdir/test-lib.sh"

fail=0

# generate input
$abs_top_builddir/tools/virsh --connect test:///default dumpxml 1 > xml || fail=1

# require the presence of the string we'll transform
grep '<vcpu>' xml > /dev/null || fail=1

sed "s/vcpu>/vcpu cpuset='aaa'>/" xml > xml-invalid || fail=1

# Require failure and a diagnostic.
$abs_top_builddir/tools/virsh --connect test:///default define xml-invalid > out 2>&1 && fail=1
cat <<\EOF > exp || fail=1
error: Failed to define domain from xml-invalid
error: internal error topology cpuset syntax error

EOF
compare exp out || fail=1

(exit $fail); exit $fail
