#!/bin/sh
# ensure that defining with an invalid vCPU cpuset elicits a diagnostic

# Copyright (C) 2008 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  virsh --version
fi

. $srcdir/test-lib.sh

fail=0

# generate input
virsh --connect test:///default dumpxml 1 > xml || fail=1

# require the presence of the string we'll transform
grep '<vcpu>' xml > /dev/null || fail=1

sed "s/vcpu>/vcpu cpuset='aaa'>/" xml > xml-invalid || fail=1

# Require failure and a diagnostic.
virsh --connect test:///default define xml-invalid > out 2>&1 && fail=1
cat <<\EOF > exp || fail=1
libvir: Domain Config error : failed Xen syscall topology cpuset syntax error
error: Failed to define domain from xml-invalid

EOF
compare out exp || fail=1

(exit $fail); exit $fail
