#!/bin/sh

: ${srcdir=$(dirname $0)}
. $srcdir/test-lib.sh
. $abs_srcdir/schematestutils.sh

DIRS=""
DIRS="$DIRS domainschemadata qemuxml2argvdata sexpr2xmldata"
DIRS="$DIRS xmconfigdata xml2sexprdata qemuxml2xmloutdata"
DIRS="$DIRS lxcxml2xmldata lxcxml2xmloutdata"
DIRS="$DIRS bhyvexml2argvdata genericxml2xmlindata genericxml2xmloutdata"
SCHEMA="domain.rng"

check_schema "$DIRS" "$SCHEMA"
