#!/bin/sh

: ${srcdir=$(dirname $0)}
. $srcdir/test-lib.sh
. $abs_srcdir/schematestutils.sh

DIRS="domainsnapshotxml2xmlin domainsnapshotxml2xmlout"
SCHEMA="domainsnapshot.rng"

check_schema "$DIRS" "$SCHEMA"
