#!/bin/sh

: ${srcdir=.}
. $srcdir/test-lib.sh
. $abs_srcdir/schematestutils.sh

DIRS="domainschemadata qemuxml2argvdata sexpr2xmldata xmconfigdata xml2sexprdata"
SCHEMA="domain.rng"

check_schema "$DIRS" "$SCHEMA"
