#!/bin/sh

: ${srcdir=.}
. $srcdir/test-lib.sh
. $abs_srcdir/schematestutils.sh

DIRS=""
DIRS="$DIRS domainschemadata qemuxml2argvdata sexpr2xmldata"
DIRS="$DIRS xmconfigdata xml2sexprdata qemuxml2xmloutdata "
DIRS="$DIRS lxcxml2xmldata"
SCHEMA="domain.rng"

check_schema "$DIRS" "$SCHEMA"
