#!/bin/sh
# Get coverage of virsh pool-define-as XML formatting

if test "$VERBOSE" = yes; then
  set -x
  virsh --version
fi

test -z "$srcdir" && srcdir=$(pwd)
test -z "$abs_top_srcdir" && abs_top_srcdir=$(pwd)/..
. "$srcdir/test-lib.sh"

fail=0

pwd=$(pwd) || fail=1

virsh --connect test:///default \
  pool-define-as --print-xml \
  P dir src-host /src/path /src/dev S /target-path \
  1>out 2>&1

cat <<EOF > pool-list-exp
<pool type='dir'>
  <name>P</name>
  <source>
    <host name='src-host'/>
    <dir path='/src/path'/>
    <device path='/src/dev'/>
    <name>S</name>
  </source>
  <target>
    <path>/target-path</path>
  </target>
</pool>

EOF

compare pool-list-exp out || fail=1

exit $fail
