#!/bin/sh
# Ensure that libvirt fails when given nonexistent --config=FILE

. "$(dirname $0)/test-lib.sh"

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/src/libvirtd --version
fi

fail=0

$abs_top_builddir/src/libvirtd --config=no-such-conf --timeout=5 2> log
RET=$?

test "$RET" != "0" && exit 0 || exit 1
