#!/bin/sh
# Ensure that libvirt fails when given nonexistent --config=FILE

if test "$VERBOSE" = yes; then
  set -x
  libvirtd --version
fi

test -z "$srcdir" && srcdir=$(pwd)
test -z "$abs_top_srcdir" && abs_top_srcdir=$(pwd)/..
. "$srcdir/test-lib.sh"

fail=0

libvirtd --config=no-such-conf --timeout=5 2> log
RET=$?

test "$RET" != "0" && exit 0 || exit 1
