#!/bin/sh
# Ensure that libvirt fails when given nonexistent --config=FILE

test -z "$srcdir" && srcdir=$(pwd)
test -z "$abs_top_srcdir" && abs_top_srcdir=$(pwd)/..
test -z "$abs_top_builddir" && abs_top_builddir=$(pwd)/..

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/daemon/libvirtd --version
fi

. "$srcdir/test-lib.sh"

fail=0

$abs_top_builddir/daemon/libvirtd --config=no-such-conf --timeout=5 2> log
RET=$?

test "$RET" != "0" && exit 0 || exit 1
