#!/bin/sh

: ${srcdir=$(dirname $0)}
. $srcdir/test-lib.sh
. $abs_srcdir/schematestutils.sh

DIRS="../src/network networkxml2xmlin networkxml2xmlout"
SCHEMA="network.rng"

check_schema "$DIRS" "$SCHEMA"
