#!/bin/sh

if [ "$#" -ne 1 ] || [ "$1" = "--help" ] || [ ! -f "$1" ]; then
    echo "This script fixes replies ids in QEMU replies files."
    echo ""
    echo "      Usage: $0 path/to/qemu.replies"
    exit 0
fi

awk -i inplace \
    'BEGIN {count=1; pattern="libvirt-[0-9]+"}
    {
        if (match($0, "libvirt-1[^0-9]")) {
            count=1;
        }
        if (match($0, pattern)) {
            str="libvirt-" count;
            sub(pattern, str, $0);
            count++;
        }
        print
    }' "$1"
