#!/bin/sh
# ensure that certain file-reading commands can handle non-seekable files

# Copyright (C) 2008 Red Hat, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

test -z "$srcdir" && srcdir=`pwd`
test -z "$abs_top_srcdir" && abs_top_srcdir=`pwd`/..
test -z "$abs_top_builddir" && abs_top_builddir=`pwd`/..

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/tools/virsh --version
fi

. "$srcdir/test-lib.sh"

fail=0

cat <<\EOF > dom
<domain type='test' id='2'>
  <name>t2</name>
  <uuid>004b96e1-2d78-c30f-5aa5-000000000000</uuid>
  <memory>8388608</memory>
  <vcpu>2</vcpu>
  <os>
    <type>xen</type>
  </os>
  <on_reboot>restart</on_reboot>
  <on_poweroff>destroy</on_poweroff>
  <on_crash>restart</on_crash>
</domain>
EOF

$abs_top_builddir/tools/virsh -c test:///default define dom > /dev/null || fail=1

mkfifo_or_skip_ fifo
cat dom > fifo &

$abs_top_builddir/tools/virsh -c test:///default define fifo > /dev/null || fail=1

(exit $fail); exit $fail
