#!/bin/sh
# blindly run each and every command listed by "virsh help"

# Copyright (C) 2008, 2009 Red Hat, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

test -z "$srcdir" && srcdir=$(pwd)

. "$srcdir/test-lib.sh"

fail=0

test_url=test:///default

$abs_top_builddir/tools/virsh -c $test_url help > cmds || framework_failure
cmds=$(sed -n 's/^    \([^ ][^ ]*\) .*/\1/p' cmds) || framework_failure
test -n "$cmds" || framework_failure

test_intro "virsh-all"

counter=0
for i in $cmds; do
    counter=`eval "expr $counter + 1"`

    # For now, just run the command and ignore output
    $abs_top_builddir/tools/virsh -c $test_url $i < /dev/null > /dev/null 2>&1
    # Temporarily ignoring exit status
    #status=$?
    status=0
    test_result $counter $i $status

    if test "$status" = "1" ; then
       fail=1
    fi
done

test_final $counter $fail

(exit $fail); exit $fail
