#!/bin/sh
# Ensure that virsh schedinfo --set invalid=val fails

# Copyright (C) 2010-2011 Red Hat, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

: ${srcdir=$(pwd)}
: ${abs_top_srcdir=$(pwd)/..}
: ${abs_top_builddir=$(pwd)/..}

# If $abs_top_builddir/tools is not early in $PATH, put it there,
# so that we can safely invoke "virsh" simply with its name.
case $PATH in
  $abs_top_builddir/tools/src:$abs_top_builddir/tools:*) ;;
  $abs_top_builddir/tools:*) ;;
  *) PATH=$abs_top_builddir/tools:$PATH; export PATH ;;
esac

if test "$VERBOSE" = yes; then
  set -x
  virsh --version
fi

. "$srcdir/test-lib.sh"

printf 'Scheduler      : fair\n\n' > exp-out || framework_failure
printf 'error: invalid scheduler option: j=k\n' > exp-err || framework_failure

fail=0

test_url=test:///default

virsh -c $test_url schedinfo 1 --set j=k >out 2>err && fail=1
compare exp-out out || fail=1
compare exp-err err || fail=1

(exit $fail); exit $fail
