#!/bin/sh
# ensure that each command's help "SYNOPSIS" line starts with the command name

# Copyright (C) 2008 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "$VERBOSE" = yes; then
  set -x
  virsh --version
fi

test -z "$srcdir" && srcdir=$(pwd)
. "$srcdir/test-lib.sh"

fail=0

test_url=test:///default

virsh -c $test_url help > cmds || framework_failure
cmds=$(sed -n 's/^    \([^ ][^ ]*\) .*/\1/p' cmds) || framework_failure
test -n "$cmds" || framework_failure

for i in $cmds; do
    virsh -c $test_url help $i > help || fail=1
    grep -A1 '^  SYNOPSIS$' help > synopsis \
      || { echo 1>&2 missing or invalid help SYNOPSIS for $i; fail=1; }
    sed -n 2p synopsis > s2 || framework_failure
    grep -E "^    $i( |$)" s2 > /dev/null \
      || { echo 1>&2 "invalid help SYNOPSIS for $i:"; cat s2 1>&2; fail=1; }
done

(exit $fail); exit $fail
