/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocol.h"

bool_t
xdr_qemud_domain_runstate (XDR *xdrs, qemud_domain_runstate *objp)
{

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_client_data_type (XDR *xdrs, qemud_packet_client_data_type *objp)
{

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_server_data_type (XDR *xdrs, qemud_packet_server_data_type *objp)
{

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_failure_reply (XDR *xdrs, qemud_packet_failure_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->message, QEMUD_MAX_ERROR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_get_version_reply (XDR *xdrs, qemud_packet_get_version_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->versionNum))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_get_node_info_reply (XDR *xdrs, qemud_packet_get_node_info_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->model, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->memory))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->cpus))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->mhz))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->nodes))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->sockets))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->cores))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->threads))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_get_capabilities_reply (XDR *xdrs, qemud_packet_get_capabilities_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->xml, QEMUD_MAX_XML_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_list_domains_reply (XDR *xdrs, qemud_packet_list_domains_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->numDomains))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->domains, QEMUD_MAX_NUM_DOMAINS,
		sizeof (int32_t), (xdrproc_t) xdr_int32_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_num_domains_reply (XDR *xdrs, qemud_packet_num_domains_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->numDomains))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_create_request (XDR *xdrs, qemud_packet_domain_create_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->xml, QEMUD_MAX_XML_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_create_reply (XDR *xdrs, qemud_packet_domain_create_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_lookup_by_id_request (XDR *xdrs, qemud_packet_domain_lookup_by_id_request *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_lookup_by_id_reply (XDR *xdrs, qemud_packet_domain_lookup_by_id_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_lookup_by_name_request (XDR *xdrs, qemud_packet_domain_lookup_by_name_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_lookup_by_name_reply (XDR *xdrs, qemud_packet_domain_lookup_by_name_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_lookup_by_uuid_request (XDR *xdrs, qemud_packet_domain_lookup_by_uuid_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_lookup_by_uuid_reply (XDR *xdrs, qemud_packet_domain_lookup_by_uuid_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_suspend_request (XDR *xdrs, qemud_packet_domain_suspend_request *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_resume_request (XDR *xdrs, qemud_packet_domain_resume_request *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_destroy_request (XDR *xdrs, qemud_packet_domain_destroy_request *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_get_info_request (XDR *xdrs, qemud_packet_domain_get_info_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_get_info_reply (XDR *xdrs, qemud_packet_domain_get_info_reply *objp)
{

	 if (!xdr_uint64_t (xdrs, &objp->cpuTime))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->runstate))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->memory))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->maxmem))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->nrVirtCpu))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_save_request (XDR *xdrs, qemud_packet_domain_save_request *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->file, PATH_MAX,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_restore_request (XDR *xdrs, qemud_packet_domain_restore_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->file, PATH_MAX,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_restore_reply (XDR *xdrs, qemud_packet_domain_restore_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_dump_xml_request (XDR *xdrs, qemud_packet_domain_dump_xml_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_dump_xml_reply (XDR *xdrs, qemud_packet_domain_dump_xml_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->xml, QEMUD_MAX_XML_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_list_defined_domains_reply (XDR *xdrs, qemud_packet_list_defined_domains_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->numDomains))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->domains, QEMUD_MAX_DOMAINS_NAME_BUF,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_num_defined_domains_reply (XDR *xdrs, qemud_packet_num_defined_domains_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->numDomains))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_start_request (XDR *xdrs, qemud_packet_domain_start_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_start_reply (XDR *xdrs, qemud_packet_domain_start_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_define_request (XDR *xdrs, qemud_packet_domain_define_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->xml, QEMUD_MAX_XML_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_define_reply (XDR *xdrs, qemud_packet_domain_define_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_undefine_request (XDR *xdrs, qemud_packet_domain_undefine_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_num_networks_reply (XDR *xdrs, qemud_packet_num_networks_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->numNetworks))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_list_networks_reply (XDR *xdrs, qemud_packet_list_networks_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->numNetworks))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->networks, QEMUD_MAX_NETWORKS_NAME_BUF,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_num_defined_networks_reply (XDR *xdrs, qemud_packet_num_defined_networks_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->numNetworks))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_list_defined_networks_reply (XDR *xdrs, qemud_packet_list_defined_networks_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->numNetworks))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->networks, QEMUD_MAX_NETWORKS_NAME_BUF,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_lookup_by_name_request (XDR *xdrs, qemud_packet_network_lookup_by_name_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_lookup_by_name_reply (XDR *xdrs, qemud_packet_network_lookup_by_name_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_lookup_by_uuid_request (XDR *xdrs, qemud_packet_network_lookup_by_uuid_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_lookup_by_uuid_reply (XDR *xdrs, qemud_packet_network_lookup_by_uuid_reply *objp)
{

	 if (!xdr_int32_t (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_create_request (XDR *xdrs, qemud_packet_network_create_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->xml, QEMUD_MAX_XML_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_create_reply (XDR *xdrs, qemud_packet_network_create_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_define_request (XDR *xdrs, qemud_packet_network_define_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->xml, QEMUD_MAX_XML_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_define_reply (XDR *xdrs, qemud_packet_network_define_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, QEMUD_MAX_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_undefine_request (XDR *xdrs, qemud_packet_network_undefine_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_start_request (XDR *xdrs, qemud_packet_network_start_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_destroy_request (XDR *xdrs, qemud_packet_network_destroy_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_dump_xml_request (XDR *xdrs, qemud_packet_network_dump_xml_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_dump_xml_reply (XDR *xdrs, qemud_packet_network_dump_xml_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->xml, QEMUD_MAX_XML_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_get_bridge_name_request (XDR *xdrs, qemud_packet_network_get_bridge_name_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_get_bridge_name_reply (XDR *xdrs, qemud_packet_network_get_bridge_name_reply *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->ifname, QEMUD_MAX_IFNAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_get_autostart_request (XDR *xdrs, qemud_packet_domain_get_autostart_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_get_autostart_reply (XDR *xdrs, qemud_packet_domain_get_autostart_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->autostart))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_domain_set_autostart_request (XDR *xdrs, qemud_packet_domain_set_autostart_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->autostart))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_get_autostart_request (XDR *xdrs, qemud_packet_network_get_autostart_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_get_autostart_reply (XDR *xdrs, qemud_packet_network_get_autostart_reply *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->autostart))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_network_set_autostart_request (XDR *xdrs, qemud_packet_network_set_autostart_request *objp)
{

	 if (!xdr_vector (xdrs, (char *)objp->uuid, QEMUD_UUID_RAW_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->autostart))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_client_data (XDR *xdrs, qemud_packet_client_data *objp)
{

	 if (!xdr_qemud_packet_client_data_type (xdrs, &objp->type))
		 return FALSE;
	switch (objp->type) {
	case QEMUD_CLIENT_PKT_GET_VERSION:
		break;
	case QEMUD_CLIENT_PKT_GET_NODEINFO:
		break;
	case QEMUD_CLIENT_PKT_LIST_DOMAINS:
		break;
	case QEMUD_CLIENT_PKT_NUM_DOMAINS:
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_CREATE:
		 if (!xdr_qemud_packet_domain_create_request (xdrs, &objp->qemud_packet_client_data_u.domainCreateRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_LOOKUP_BY_ID:
		 if (!xdr_qemud_packet_domain_lookup_by_id_request (xdrs, &objp->qemud_packet_client_data_u.domainLookupByIDRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_LOOKUP_BY_UUID:
		 if (!xdr_qemud_packet_domain_lookup_by_uuid_request (xdrs, &objp->qemud_packet_client_data_u.domainLookupByUUIDRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_LOOKUP_BY_NAME:
		 if (!xdr_qemud_packet_domain_lookup_by_name_request (xdrs, &objp->qemud_packet_client_data_u.domainLookupByNameRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_SUSPEND:
		 if (!xdr_qemud_packet_domain_suspend_request (xdrs, &objp->qemud_packet_client_data_u.domainSuspendRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_RESUME:
		 if (!xdr_qemud_packet_domain_resume_request (xdrs, &objp->qemud_packet_client_data_u.domainResumeRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_DESTROY:
		 if (!xdr_qemud_packet_domain_destroy_request (xdrs, &objp->qemud_packet_client_data_u.domainDestroyRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_GET_INFO:
		 if (!xdr_qemud_packet_domain_get_info_request (xdrs, &objp->qemud_packet_client_data_u.domainGetInfoRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_SAVE:
		 if (!xdr_qemud_packet_domain_save_request (xdrs, &objp->qemud_packet_client_data_u.domainSaveRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_RESTORE:
		 if (!xdr_qemud_packet_domain_restore_request (xdrs, &objp->qemud_packet_client_data_u.domainRestoreRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DUMP_XML:
		 if (!xdr_qemud_packet_domain_dump_xml_request (xdrs, &objp->qemud_packet_client_data_u.domainDumpXMLRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_LIST_DEFINED_DOMAINS:
		break;
	case QEMUD_CLIENT_PKT_NUM_DEFINED_DOMAINS:
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_START:
		 if (!xdr_qemud_packet_domain_start_request (xdrs, &objp->qemud_packet_client_data_u.domainStartRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_DEFINE:
		 if (!xdr_qemud_packet_domain_define_request (xdrs, &objp->qemud_packet_client_data_u.domainDefineRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_UNDEFINE:
		 if (!xdr_qemud_packet_domain_undefine_request (xdrs, &objp->qemud_packet_client_data_u.domainUndefineRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NUM_NETWORKS:
		break;
	case QEMUD_CLIENT_PKT_LIST_NETWORKS:
		break;
	case QEMUD_CLIENT_PKT_NUM_DEFINED_NETWORKS:
		break;
	case QEMUD_CLIENT_PKT_LIST_DEFINED_NETWORKS:
		break;
	case QEMUD_CLIENT_PKT_NETWORK_LOOKUP_BY_UUID:
		 if (!xdr_qemud_packet_network_lookup_by_uuid_request (xdrs, &objp->qemud_packet_client_data_u.networkLookupByUUIDRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_LOOKUP_BY_NAME:
		 if (!xdr_qemud_packet_network_lookup_by_name_request (xdrs, &objp->qemud_packet_client_data_u.networkLookupByNameRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_CREATE:
		 if (!xdr_qemud_packet_network_create_request (xdrs, &objp->qemud_packet_client_data_u.networkCreateRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_DEFINE:
		 if (!xdr_qemud_packet_network_define_request (xdrs, &objp->qemud_packet_client_data_u.networkDefineRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_UNDEFINE:
		 if (!xdr_qemud_packet_network_undefine_request (xdrs, &objp->qemud_packet_client_data_u.networkUndefineRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_START:
		 if (!xdr_qemud_packet_network_start_request (xdrs, &objp->qemud_packet_client_data_u.networkStartRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_DESTROY:
		 if (!xdr_qemud_packet_network_destroy_request (xdrs, &objp->qemud_packet_client_data_u.networkDestroyRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_DUMP_XML:
		 if (!xdr_qemud_packet_network_dump_xml_request (xdrs, &objp->qemud_packet_client_data_u.networkDumpXMLRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_GET_BRIDGE_NAME:
		 if (!xdr_qemud_packet_network_get_bridge_name_request (xdrs, &objp->qemud_packet_client_data_u.networkGetBridgeNameRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_GET_AUTOSTART:
		 if (!xdr_qemud_packet_domain_get_autostart_request (xdrs, &objp->qemud_packet_client_data_u.domainGetAutostartRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_DOMAIN_SET_AUTOSTART:
		 if (!xdr_qemud_packet_domain_set_autostart_request (xdrs, &objp->qemud_packet_client_data_u.domainSetAutostartRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_GET_AUTOSTART:
		 if (!xdr_qemud_packet_network_get_autostart_request (xdrs, &objp->qemud_packet_client_data_u.networkGetAutostartRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_NETWORK_SET_AUTOSTART:
		 if (!xdr_qemud_packet_network_set_autostart_request (xdrs, &objp->qemud_packet_client_data_u.networkSetAutostartRequest))
			 return FALSE;
		break;
	case QEMUD_CLIENT_PKT_GET_CAPABILITIES:
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_qemud_packet_server_data (XDR *xdrs, qemud_packet_server_data *objp)
{

	 if (!xdr_qemud_packet_server_data_type (xdrs, &objp->type))
		 return FALSE;
	switch (objp->type) {
	case QEMUD_SERVER_PKT_FAILURE:
		 if (!xdr_qemud_packet_failure_reply (xdrs, &objp->qemud_packet_server_data_u.failureReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_GET_VERSION:
		 if (!xdr_qemud_packet_get_version_reply (xdrs, &objp->qemud_packet_server_data_u.getVersionReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_GET_NODEINFO:
		 if (!xdr_qemud_packet_get_node_info_reply (xdrs, &objp->qemud_packet_server_data_u.getNodeInfoReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_LIST_DOMAINS:
		 if (!xdr_qemud_packet_list_domains_reply (xdrs, &objp->qemud_packet_server_data_u.listDomainsReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NUM_DOMAINS:
		 if (!xdr_qemud_packet_num_domains_reply (xdrs, &objp->qemud_packet_server_data_u.numDomainsReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_CREATE:
		 if (!xdr_qemud_packet_domain_create_reply (xdrs, &objp->qemud_packet_server_data_u.domainCreateReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_LOOKUP_BY_ID:
		 if (!xdr_qemud_packet_domain_lookup_by_id_reply (xdrs, &objp->qemud_packet_server_data_u.domainLookupByIDReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_LOOKUP_BY_UUID:
		 if (!xdr_qemud_packet_domain_lookup_by_uuid_reply (xdrs, &objp->qemud_packet_server_data_u.domainLookupByUUIDReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_LOOKUP_BY_NAME:
		 if (!xdr_qemud_packet_domain_lookup_by_name_reply (xdrs, &objp->qemud_packet_server_data_u.domainLookupByNameReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_SUSPEND:
		break;
	case QEMUD_SERVER_PKT_DOMAIN_RESUME:
		break;
	case QEMUD_SERVER_PKT_DOMAIN_DESTROY:
		break;
	case QEMUD_SERVER_PKT_DOMAIN_GET_INFO:
		 if (!xdr_qemud_packet_domain_get_info_reply (xdrs, &objp->qemud_packet_server_data_u.domainGetInfoReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_SAVE:
		break;
	case QEMUD_SERVER_PKT_DOMAIN_RESTORE:
		 if (!xdr_qemud_packet_domain_restore_reply (xdrs, &objp->qemud_packet_server_data_u.domainRestoreReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DUMP_XML:
		 if (!xdr_qemud_packet_domain_dump_xml_reply (xdrs, &objp->qemud_packet_server_data_u.domainDumpXMLReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_LIST_DEFINED_DOMAINS:
		 if (!xdr_qemud_packet_list_defined_domains_reply (xdrs, &objp->qemud_packet_server_data_u.listDefinedDomainsReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NUM_DEFINED_DOMAINS:
		 if (!xdr_qemud_packet_num_defined_domains_reply (xdrs, &objp->qemud_packet_server_data_u.numDefinedDomainsReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_START:
		 if (!xdr_qemud_packet_domain_start_reply (xdrs, &objp->qemud_packet_server_data_u.domainStartReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_DEFINE:
		 if (!xdr_qemud_packet_domain_define_reply (xdrs, &objp->qemud_packet_server_data_u.domainDefineReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_UNDEFINE:
		break;
	case QEMUD_SERVER_PKT_NUM_NETWORKS:
		 if (!xdr_qemud_packet_num_networks_reply (xdrs, &objp->qemud_packet_server_data_u.numNetworksReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_LIST_NETWORKS:
		 if (!xdr_qemud_packet_list_networks_reply (xdrs, &objp->qemud_packet_server_data_u.listNetworksReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NUM_DEFINED_NETWORKS:
		 if (!xdr_qemud_packet_num_defined_networks_reply (xdrs, &objp->qemud_packet_server_data_u.numDefinedNetworksReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_LIST_DEFINED_NETWORKS:
		 if (!xdr_qemud_packet_list_defined_networks_reply (xdrs, &objp->qemud_packet_server_data_u.listDefinedNetworksReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NETWORK_LOOKUP_BY_UUID:
		 if (!xdr_qemud_packet_network_lookup_by_uuid_reply (xdrs, &objp->qemud_packet_server_data_u.networkLookupByUUIDReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NETWORK_LOOKUP_BY_NAME:
		 if (!xdr_qemud_packet_network_lookup_by_name_reply (xdrs, &objp->qemud_packet_server_data_u.networkLookupByNameReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NETWORK_CREATE:
		 if (!xdr_qemud_packet_network_create_reply (xdrs, &objp->qemud_packet_server_data_u.networkCreateReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NETWORK_DEFINE:
		 if (!xdr_qemud_packet_network_define_reply (xdrs, &objp->qemud_packet_server_data_u.networkDefineReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NETWORK_UNDEFINE:
		break;
	case QEMUD_SERVER_PKT_NETWORK_START:
		break;
	case QEMUD_SERVER_PKT_NETWORK_DESTROY:
		break;
	case QEMUD_SERVER_PKT_NETWORK_DUMP_XML:
		 if (!xdr_qemud_packet_network_dump_xml_reply (xdrs, &objp->qemud_packet_server_data_u.networkDumpXMLReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NETWORK_GET_BRIDGE_NAME:
		 if (!xdr_qemud_packet_network_get_bridge_name_reply (xdrs, &objp->qemud_packet_server_data_u.networkGetBridgeNameReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_GET_AUTOSTART:
		 if (!xdr_qemud_packet_domain_get_autostart_reply (xdrs, &objp->qemud_packet_server_data_u.domainGetAutostartReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_DOMAIN_SET_AUTOSTART:
		break;
	case QEMUD_SERVER_PKT_NETWORK_GET_AUTOSTART:
		 if (!xdr_qemud_packet_network_get_autostart_reply (xdrs, &objp->qemud_packet_server_data_u.networkGetAutostartReply))
			 return FALSE;
		break;
	case QEMUD_SERVER_PKT_NETWORK_SET_AUTOSTART:
		break;
	case QEMUD_SERVER_PKT_GET_CAPABILITIES:
		 if (!xdr_qemud_packet_get_capabilities_reply (xdrs, &objp->qemud_packet_server_data_u.getCapabilitiesReply))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_qemud_packet_client (XDR *xdrs, qemud_packet_client *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->serial))
		 return FALSE;
	 if (!xdr_qemud_packet_client_data (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_server (XDR *xdrs, qemud_packet_server *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->serial))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->inReplyTo))
		 return FALSE;
	 if (!xdr_qemud_packet_server_data (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_qemud_packet_header (XDR *xdrs, qemud_packet_header *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->length))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->prog))
		 return FALSE;
	return TRUE;
}
