/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "protocol.h"

bool_t
xdr_qemud_packet_header (XDR *xdrs, qemud_packet_header *objp)
{

	 if (!xdr_uint32_t (xdrs, &objp->length))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->prog))
		 return FALSE;
	return TRUE;
}
