/* Automatically generated by remote_generator.pl.
 * Do not edit this file.  Any changes you make will be lost.
 */

static int qemuDispatchMonitorCommand(
    struct qemud_server *server,
    struct qemud_client *client,
    virConnectPtr conn,
    remote_message_header *hdr,
    remote_error *rerr,
    qemu_monitor_command_args *args,
    qemu_monitor_command_ret *ret);
