/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RP_QEMU_H_RPCGEN
#define _RP_QEMU_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include "internal.h"
#include "remote_protocol.h"
#include <arpa/inet.h>

struct qemu_monitor_command_args {
        remote_nonnull_domain domain;
        remote_nonnull_string cmd;
        int flags;
};
typedef struct qemu_monitor_command_args qemu_monitor_command_args;

struct qemu_monitor_command_ret {
        remote_nonnull_string result;
};
typedef struct qemu_monitor_command_ret qemu_monitor_command_ret;
#define QEMU_PROGRAM 0x20008087
#define QEMU_PROTOCOL_VERSION 1

enum qemu_procedure {
        QEMU_PROC_MONITOR_COMMAND = 1,
};
typedef enum qemu_procedure qemu_procedure;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_qemu_monitor_command_args (XDR *, qemu_monitor_command_args*);
extern  bool_t xdr_qemu_monitor_command_ret (XDR *, qemu_monitor_command_ret*);
extern  bool_t xdr_qemu_procedure (XDR *, qemu_procedure*);

#else /* K&R C */
extern bool_t xdr_qemu_monitor_command_args ();
extern bool_t xdr_qemu_monitor_command_ret ();
extern bool_t xdr_qemu_procedure ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RP_QEMU_H_RPCGEN */
